---
- name: install packages build-essential
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  with_items:
    - build-essential
    - g++
    - git
    - git-core
    - libssl-dev
    - libqt4-dev
    - libc6-dev
    - automake
    - libtool
    - zlib1g
    - zlib1g-dev
    - openssl
    - libssl-dev
    - libreadline-dev
    - libxml2-dev
    - libxslt1-dev
    - libncurses5-dev
    - pkg-config
    - chrpath
    - libfontconfig1-dev
    - libxft-dev
    - libpq-dev

- name: install rbenv
  git: repo=https://github.com/sstephenson/rbenv.git
       dest={{ vagrant_home }}/.rbenv
       version=master

- name: add rbenv path to bash_profile
  #copy: src=../files/rbenv.sh dest=/etc/profile.d/rbenv.sh
  copy: content="export PATH=\"/home/vagrant/.rbenv/bin:$PATH\"\neval \"$(rbenv init -)\"" dest=/etc/profile.d/rbenv.sh

- name: install ruby_build
  git: repo=https://github.com/sstephenson/ruby-build.git
       dest={{ vagrant_home }}/.rbenv/plugins/ruby-build
       version=master

- name: install ruby
  shell: "export RBENV_ROOT={{ vagrant_home }}/.rbenv; export PATH=$RBENV_ROOT/bin:$PATH; echo N | rbenv install {{ ruby_version }}; rbenv global {{ ruby_version }}"
  args:
    creates: "{{ vagrant_home }}/.rbenv/versions/{{ ruby_version }}/"

- name: install bundler
  shell: "{{ vagrant_home }}/.rbenv/shims/gem install bundler"
  args:
    creates: "{{ vagrant_home }}/.rbenv/shims/bundle"

- name: change ~/.rbenv owner to vagrant
  file: path={{ vagrant_home }}/.rbenv state=directory owner=vagrant group=vagrant recurse=yes
