---

- name: enable git branch color
  template: src=git_branch.sh dest=/etc/profile.d/git_branch.sh

- name: source profile
  lineinfile: >
    dest={{ vagrant_home }}/.bashrc
    line='source /etc/profile'
