---
- name: Docker group should exist
  group: name=docker state=present

- name: Vagrant should be a member of docker group
  user: name=vagrant groups=docker state=present

- name: Docker should be installed
  apt: name=docker-engine state=present force=yes

- name: Docker should be running
  service: name=docker state=started enabled=yes

- name: Ensure docker-compose is installed and available
  get_url:
    # url : https://github.com/docker/compose/releases/download/1.7.0-rc1/docker-compose-{{ ansible_system }}-{{ ansible_userspace_architecture }}
    url : https://github.com/docker/compose/releases/download/1.8.1/docker-compose-Linux-x86_64
    validate_certs: no
    dest: /usr/local/bin/docker-compose
- name: Ensure docker-compose is executable
  file: path=/usr/local/bin/docker-compose state=touch mode=0755
