- hosts: 127.0.0.1
  connection: local
  sudo: yes
  vars:
    vagrant_home: "/home/vagrant"
    nvm_install_dir: /opt/nvm
    src_dir: /usr/local/src
    nvm_node_version: 6.1.0
    nvm_version: 0.32.0
    ruby_version: 2.3.1
    emacs_version: 24.4
  roles:
    - misc
    - docker
    - rbenv
    - node
    - emacs
