---

- name: check exist emacs source file
  command: ls -l {{src_dir}}/emacs-{{emacs_version}}.tar.gz
  ignore_errors: yes
  register: result1

- name: get emacs source file
  command: chdir={{src_dir}} wget http://ftp.jaist.ac.jp/pub/GNU/emacs/emacs-{{ emacs_version }}.tar.gz
  when: result1|failed

- name: extract gz
  command: chdir={{src_dir}} tar xvf emacs-{{emacs_version}}.tar.gz
  when: result1|failed

- name: check emacs install
  command: which emacs
  ignore_errors: yes
  register: result2

- name: expand emacs src
  command: chdir={{src_dir}} tar xvf emacs-{{emacs_version}}.tar.gz
  when: result2|failed

- name: comfigure emacs
  command: chdir={{src_dir}}/emacs-{{emacs_version}} ./configure --with-x-toolkit=no --with-xpm=no --with-jpeg=no --with-gif=no --with-tiff=no
  when: result2|failed

- name: make emacs
  command: chdir={{src_dir}}/emacs-{{emacs_version}} make
  when: result2|failed

- name: install emacs
  command: chdir={{src_dir}}/emacs-{{emacs_version}} make install
  when: result2|failed

- name: check exist cask file
  command: ls -l {{ vagrant_home }}/.install_cask
  sudo: yes
  sudo_user: vagrant
  ignore_errors: yes
  register: has_cask

- name: download cask
  command: chdir={{ vagrant_home }} wget https://raw.githubusercontent.com/cask/cask/master/go -O .install_cask
  sudo: yes
  sudo_user: vagrant
  when: has_cask|failed

- name: install cask
  command: chdir={{ vagrant_home }} python .install_cask
  sudo: yes
  sudo_user: vagrant
  when: has_cask|failed

- name: set .emacs
  template: src=.emacs dest={{ vagrant_home }}/.emacs
  sudo: yes
  sudo_user: vagrant

- name: check exist Cask file
  command: ls -l {{ vagrant_home }}/.emacs.d/Cask
  sudo: yes
  sudo_user: vagrant
  ignore_errors: yes
  register: has_caskfile

- name: remove .emacs.d
  file: path={{ vagrant_home }}/.emacs.d state=absent
  when: has_caskfile|failed
  sudo: yes
  sudo_user: vagrant

- name: cloning .emacs.d
  command: chdir={{ vagrant_home }} git clone https://github.com/TongTheDopeness/cask.git .emacs.d
  when: has_caskfile|failed
  sudo: yes
  sudo_user: vagrant

- name: set cask path
  lineinfile: >
    dest={{ vagrant_home }}/.bashrc
    line='export PATH=$HOME/.cask/bin:$PATH'

- name: cask install
  command: chdir={{ vagrant_home }}/.emacs.d  source {{ vagrant_home }}/.bashrc && cask install executable=/bin/bash
  sudo: yes
  sudo_user: vagrant
